GLOBAL_CONTEXT = []
TARGET_FILES = []
ENTITIES = []
CHAT_HISTORY = {}
APPROXIMATION_FORMAT_EXAMPLES = []
LOOP_PERF_EXAMPLES = []
NEW_TECHNIQUE_EXAMPLES = []
CODE_BASE_SUMMARY = []

TARGET_FUNCTIONS_SCRIPT = ""
PURPOSE_IDENTIFICATION_SCRIPT = ""
ANNOTATION_SCRIPT = ""
PLANNING_SCRIPT = ""
APPROXIMATION_SCRIPT = ""

PLATFORM_ARCHITECTURE = "MSP 430"